cli: Add --json support to --check
containers/bootc pull request #472
Opened 2024-04-16 23:26 UTC by travier

This will let higher level tools (Plasma Discover for example) more easily read the output of `bootc update --check --json`.

---

Needs https://github.com/ostreedev/ostree-rs-ext/pull/618

2024-04-17 13:05 UTC, cgwalters commented
The original idea here is that the result of `--check` is cached, so you can just run `bootc status --json` to get that data after invoking `bootc upgrade --check`.  So I don't believe we need this, agreed?

2024-04-17 13:16 UTC, travier commented
Thanks for pointing that. Will have to give this a try then.

2024-04-17 14:01 UTC, cgwalters commented
However, right now we don't expose the diff in the status.  I think it would likely make sense to do that.  There's a bit of a messy thing here as we would need to probably change `cached_update` to be its own struct.  

Also this relates to https://github.com/ostreedev/ostree-rs-ext/pull/618 in that in the end we'd need to create a new `ContainerImageDiff` structure here anyways (because the API types for this crate need to be abstracted from those of ostree).

2024-04-17 14:49 UTC, cgwalters commented
> But does bootc offer an unprivileged path right now?

No.  Historically the polkit/unprivileged stuff in both rpm-ostree and things like PackageKit are big, complex beasts that add a lot of security-sensitive code paths. My thinking here is that for now such a thing is probably best as a separate project on top of bootc.  Or maybe we could add it as an optionally-installed secondary component here.

One thing I would say on this is that I also think many of the same concerns should apply to "workload" containers such as podman; ideally we share code there.  Access to the podman (and docker) remote API is equivalent to root in practice right now, note.   It may make sense to have a single component which can initiate upgrades for bootc as well as wrap e.g. https://docs.podman.io/en/latest/markdown/podman-auto-update.1.html (i.e. no ability to change system state, just do updates)

2024-04-17 14:58 UTC, travier commented
Creating a small daemon with a very limited, unprivileged DBus API would make sense. For GNOME Software/Plasma Discover, we mostly need "check for update" & "update" commands. And maybe something for "rebase/switch", but it would be hard to make this one unprivileged.

2024-04-17 14:59 UTC, travier commented
Might be needed to coordinate with the dnf team here. They already have a DBus daemon that does (a larger subset of) that.

2024-04-26 15:16 UTC, cgwalters requested changes
> However, right now we don't expose the diff in the status.

This is what we should do.

2024-12-03 20:01 UTC, cgwalters commented
I believe https://github.com/containers/bootc/pull/472#issuecomment-2061219087 covers this, please reopen if anyone disagrees.

2024-12-03 20:01 UTC, closed without merging

2024-12-03 20:06 UTC, cgwalters commented
https://github.com/containers/bootc/issues/932 tracks the diff