bootloader: Identify prep partition on loop device
containers/bootc pull request #702
Opened 2024-07-17 17:56 UTC by sacsant

While writing a bootc image to a qcow2 file, required partitions are
created using a loop device. On ppc64le arch the type value used
for prep boot partition is 41.

"partitions": [
         {
            "node": "/dev/loop0p1",
            "start": 2048,
            "size": 8192,
            "type": "41",
            "bootable": true
         },{
            "node": "/dev/loop0p2",

Expand the PReP Boot partition check logic to ensure bootloader
specific files are correctly written when a loop device is used.

2024-07-17 18:00 UTC, sacsant commented
Writing to a qcow2 image the bootloader specific information is correctly written to first partition (/dev/loop0p1)

Deploying container image...Freed objects: 118 bytes
done
Running bootupctl to install bootloader
> bootupctl backend install --write-uuid --device /dev/loop0p1 /run/osbuild/mounts
Installed: grub.cfg
Trimming mounts

2024-07-17 18:03 UTC, cgwalters commented
> While writing a bootc image to a qcow2 file

You mean specifically with bootc-image-builder, correct? I think the real bug is https://github.com/osbuild/bootc-image-builder/pull/497#discussion_r1681487157

2024-07-17 19:34 UTC, cgwalters requested changes
Marking as changes requested so this shows up as reviewed, but to be clear I may be wrong about something so feel free to push back!

2024-07-18 06:06 UTC, sacsant commented
> > While writing a bootc image to a qcow2 file
> 
> You mean specifically with bootc-image-builder, correct? I think the real bug is [osbuild/bootc-image-builder#497 (comment)](https://github.com/osbuild/bootc-image-builder/pull/497#discussion_r1681487157)
> 

Yes, using bootc-image-builder. 

> (And the GPT type UUID should match)

Both dos and gpt are supported types. So yes, this can be changed to GPT (and the partition Type values 41 and 83 to 9E1A2D38-C612-4316-AA26-8B49521E5A8B & 0FC63DAF-8483-4772-8E79-3D69D8477DE4 respectively).

Let me know which is preferred?

2024-07-18 14:12 UTC, sacsant commented
Have updated the bootc-image-builder PR to use gpt format instead of dos. Closing this PR.

2024-07-18 14:12 UTC, closed without merging