status: Rework human readable output
containers/bootc pull request #901
Opened 2024-11-17 22:28 UTC by cgwalters

- Add a circle like rpm-ostree
- Add a whitespace line between entries
- Drop not-present entries
- Rework timestamp+version combo; if there's no version, then show the column as `Timestamp`; if there's a version but no timestamp, just omit the timestamp
- Align columns

Closes: https://github.com/containers/bootc/issues/900

2024-11-17 22:48 UTC, tulilirockz commented
Looks absolutely great!

2024-11-18 14:37 UTC, djach7 requested changes
LGTM other than requested if statement change

2024-11-18 17:57 UTC, cgwalters commented on lib/src/glyph.rs
> +            f.write_str(self.as_ascii())
Well spotted! This is why we have code review :smile: 

So...somehow this function is returning we're *not* in a UTF-8 locale in most cases I've tried (with `env LANG=C.UTF-8` e.g.) and so the logic inversion was cancelling out for me and I was getting the expected UTF-8 display.

I only started down this rabbit hole, but in practice we use Unicode at least in other places so for now I just dropped the non-Unicode support.

2024-11-18 18:31 UTC, djach7 approved these changes
LGTM! Thanks for updating all of this and making it look much better

2024-11-18 19:31 UTC, merged